### ISSUE TITLE
Better activate it by default

### ISSUE THREAD

**Issue by pcav** [Septima/qgis-wedgebuffer#1]
Upon installation, the provider is inactivated within Processing, thus difficult to find.

**Comment by AsgerPetersen** [comment]
Hi @pcav Thank you for commenting. I would really like to enable the provider by default, but I have not found out how to do that. Could you give me a pointer?

**Comment by pcav** [comment]
@volaya can probably help you better then mine, otherwise please ask qgis-dev mailing list

**Comment by AsgerPetersen** [comment]
@pcav Thank you!

**Comment by Gustry** [comment]
I just found this issue. It's this line : https://github.com/Septima/qgis-wedgebuffer/blob/master/src/WedgeBuffer/wedge_buffer_provider.py#L45

**Comment by AsgerPetersen** [comment]
Thank you @Gustry ! That was awfully obvious :-)

**Comment by Gustry** [comment]
Welcome !
