### ISSUE TITLE
Plugin not showing up

### ISSUE THREAD

**Issue by szmolnar** [Septima/qgis-wedgebuffer#2]
Hi!

I installed the plugin under QGIS 2.14 and I activated it's processing provider but the plugin it is not showing up in the processing toolbox.

**Comment by AsgerPetersen** [comment]
Hi @szmolnar 

Thank you for reporting this.

It is a bit difficult to debug without more information. Could you please check that the provider is activated like
![image](https://cloud.githubusercontent.com/assets/1392735/14540353/e429a6a0-0284-11e6-84f1-7cdeaf05b777.png)

And that you are looking for the plugin under the "Advanced interface" like 
![image](https://cloud.githubusercontent.com/assets/1392735/14540420/3a69777a-0285-11e6-92d3-f01f02b6e584.png)

Alternatively you can try using the search box of the Processing Toolbox to search for "Wedge"
![image](https://cloud.githubusercontent.com/assets/1392735/14540475/8044b674-0285-11e6-92c5-77acb9be6edd.png)

**Comment by szmolnar** [comment]
Hi!

Well, It’s a shame I missed the advanced interface option. I don’t even know how, I must have been tired :-)

Thanks!

**Comment by AsgerPetersen** [comment]
@szmolnar No problem :-)

Closing this issue.

**Comment by szmolnar** [comment]
Hi!

Is is possible that the tool is limited to max 3 “sectors”?
When I create a list with 3 sectors it is processed fine by “Wedge Buffer” and It will generate it’s table correctly

When I add a 4th sector it will cause a problem in processing and only the last one will be processed as below:

Since I would like to make a more sophisticated representation of radio cells it would be grate feature to be able to add more “unlimited” sectors and possibly an option to be able to set sepparate colors for each. 

Thanks!
