### ISSUE TITLE
Sorry didn`t understand how to change Radius Field or

### ISSUE THREAD

**Issue by evgeniusb** [Septima/qgis-wedgebuffer#3]
this function doesn`t work. I tried to create sectors, my Radius Field was equal to 0.1, 10, 100 but as a result all sectors were overlapped with radius approx = 220 kilometers. Could you update readme file to describe in details this field? 
Or help me please.

**Comment by AsgerPetersen** [comment]
@evgeniusb You figured it out?

**Comment by evgeniusb** [comment]
Yes, thank you. It was my mistake, sorry.
